name = "xrw-album-workers"
main = "src/worker.js"
compatibility_date = "2026-08-20"

[assets]
directory = "./public"
binding = "ASSETS"
not_found_handling = "single-page-application"

[[d1_databases]]
binding = "DB"
database_name = "xrw-album"
database_id = "8ad3bd59-d501-4397-898a-e895aca1291f"
migrations_dir = "migrations"
